### ISSUE TITLE
Website not mobile-friendly

### ISSUE THREAD

**Issue by qbilius** [brain-score/brain-score#115]
Table doesn't fit on screen yet there is no horizontal scrollbar.
Tested on Firefox.

Possible solution (wild guess):

```css
body {
  overflow:auto;
}
```
